Repository jenkinsci/json-lib, pull requests merged in 2024-04, with the labels that each got.

#9 Remove `jdk15` directory
  pom.xml
  src/main/java/net/sf/json/JSONArray.java
  src/main/java/net/sf/json/JSONObject.java
  src/main/java/net/sf/json/util/EnumMorpher.java
  src/test/java/net/sf/json/TestGenerics.java
  src/test/java/net/sf/json/TestJSONArrayCollection.java
  src/test/java/net/sf/json/TestJSONArrayJdk15.java
  src/test/java/net/sf/json/TestJSONObjectJdk15.java
  src/test/java/net/sf/json/bugs/TestBug2843623.java
  src/test/java/net/sf/json/sample/AnnotatedBean.java
  src/test/java/net/sf/json/sample/AnnotationBean.java
  src/test/java/net/sf/json/sample/EnumBean.java
  src/test/java/net/sf/json/sample/GenericsBean.java
  src/test/java/net/sf/json/sample/JsonAnnotation.java
  src/test/java/net/sf/json/sample/JsonEnum.java
Labels: skip-changelog

#7 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: skip-changelog

#20 Remove unused files
  .cvsignore
  .hgignore
  build.gradle
  build.properties
  build.xml
  deploy.sh
  extensions/spring/.cvsignore
  extensions/spring/deploy.sh
  extensions/spring/pom.xml
  extensions/spring/src/main/java/net/sf/json/spring/web/servlet/view/JsonView.java
  extensions/spring/src/test/java/net/sf/json/spring/web/servlet/view/JsonViewTest.java
  extensions/spring/src/test/resources/log4j.properties
  net.sf.json-lib.sh
  src/lib/jarjar-1.0.jar
  src/lib/maven-ant-tasks-2.0.9.jar
  src/main/groovy/net/sf/json/groovy/GJson.groovy
  src/site/site.xml
  src/site/xdoc/package.xml
  src/test/groovy/net/sf/json/groovy/AllTests.groovy
  src/test/groovy/net/sf/json/groovy/Book.groovy
  src/test/groovy/net/sf/json/groovy/TestJSONArrayGroovy.groovy
  src/test/groovy/net/sf/json/groovy/TestJSONObjectGroovy.groovy
  src/test/groovy/net/sf/json/groovy/TestJsonGroovyBuilder.groovy
  src/test/groovy/net/sf/json/groovy/TestJsonSlurper.groovy
  src/test/groovy/net/sf/json/groovy/TestMetaClasses.groovy
Labels: skip-changelog

#21 Upgrade XMLUnit from 1.6 to 2.9.1
  pom.xml
Labels: dependencies, java

#24 Modernize package info
  src/main/java/net/sf/ezmorph/array/package-info.java
  src/main/java/net/sf/ezmorph/array/package.html
  src/main/java/net/sf/ezmorph/bean/package-info.java
  src/main/java/net/sf/ezmorph/bean/package.html
  src/main/java/net/sf/ezmorph/object/package-info.java
  src/main/java/net/sf/ezmorph/object/package.html
  src/main/java/net/sf/ezmorph/package-info.java
  src/main/java/net/sf/ezmorph/package.html
  src/main/java/net/sf/ezmorph/primitive/package-info.java
  src/main/java/net/sf/ezmorph/primitive/package.html
  src/main/java/net/sf/ezmorph/test/package-info.java
  src/main/java/net/sf/ezmorph/test/package.html
  src/main/java/net/sf/json/filters/package-info.java
  src/main/java/net/sf/json/filters/package.html
  src/main/java/net/sf/json/groovy/package-info.java
  src/main/java/net/sf/json/groovy/package.html
  src/main/java/net/sf/json/package-info.java
  src/main/java/net/sf/json/package.html
  src/main/java/net/sf/json/processors/package-info.java
  src/main/java/net/sf/json/processors/package.html
  src/main/java/net/sf/json/regexp/package-info.java
  src/main/java/net/sf/json/regexp/package.html
  src/main/java/net/sf/json/test/package-info.java
  src/main/java/net/sf/json/test/package.html
  src/main/java/net/sf/json/util/package-info.java
  src/main/java/net/sf/json/util/package.html
  src/main/java/net/sf/json/xml/package-info.java
  src/main/java/net/sf/json/xml/package.html
Labels: internal

#26 Add `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: skip-changelog

#28 Fix Javadoc generation on Java 11
  src/main/java/net/sf/json/JSONArray.java
  src/main/java/net/sf/json/JSONObject.java
  src/main/java/net/sf/json/util/JavaIdentifierTransformer.java
  src/main/java/net/sf/json/util/PropertySetStrategy.java
  src/main/java/net/sf/json/util/WebUtils.java
Labels: internal

#29 Remove usage of `NestableRuntimeException`
  src/main/java/net/sf/ezmorph/MorphException.java
  src/main/java/net/sf/json/JSONException.java
  src/main/java/net/sf/json/regexp/Perl5RegexpMatcher.java
Labels: internal

#31 Remove support for JDK 1.3
  pom.xml
  src/main/java/net/sf/json/regexp/Perl5RegexpMatcher.java
  src/main/java/net/sf/json/regexp/RegexpUtils.java
  src/test/java/net/sf/json/regexp/AllTests.java
  src/test/java/net/sf/json/regexp/TestPerl5RegexpMatcher.java
Labels: internal

#32 Remove `commons-httpclient` test dependency
  pom.xml
Labels: internal

#33 Add type parameters
  src/main/java/net/sf/json/JSONObject.java
Labels: internal

#35 Remove some usages of `StringUtils`
  src/main/java/net/sf/json/JsonConfig.java
  src/main/java/net/sf/json/test/JSONAssert.java
  src/main/java/net/sf/json/xml/XMLSerializer.java
Labels: internal

#38 Revert part of #33
  src/main/java/net/sf/json/JSONObject.java
Labels: bug
