Repository jenkinsci/json-lib, pull requests merged in 2025-07, with the labels that each got.

#34 Reduce usages of `commons-collections`
  src/main/java/net/sf/json/JSONObject.java
Labels: internal

#40 Reduce usages of `EqualsBuilder` and `HashCodeBuilder`
  src/main/java/net/sf/ezmorph/array/BooleanArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/BooleanObjectArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/ByteArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/CharArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/CharacterObjectArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/DoubleArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/FloatArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/IntArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/LongArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/ObjectArrayMorpher.java
  src/main/java/net/sf/ezmorph/array/ShortArrayMorpher.java
  src/main/java/net/sf/ezmorph/object/BigDecimalMorpher.java
  src/main/java/net/sf/ezmorph/object/BigIntegerMorpher.java
  src/main/java/net/sf/ezmorph/object/BooleanObjectMorpher.java
  src/main/java/net/sf/ezmorph/object/CharacterObjectMorpher.java
  src/main/java/net/sf/ezmorph/object/MapToDateMorpher.java
  src/main/java/net/sf/ezmorph/object/ObjectListMorpher.java
  src/main/java/net/sf/ezmorph/primitive/BooleanMorpher.java
  src/main/java/net/sf/ezmorph/primitive/ByteMorpher.java
  src/main/java/net/sf/ezmorph/primitive/CharMorpher.java
  src/main/java/net/sf/ezmorph/primitive/DoubleMorpher.java
  src/main/java/net/sf/ezmorph/primitive/FloatMorpher.java
  src/main/java/net/sf/ezmorph/primitive/IntMorpher.java
  src/main/java/net/sf/ezmorph/primitive/LongMorpher.java
  src/main/java/net/sf/ezmorph/primitive/ShortMorpher.java
Labels: internal

#36 Remove `XMLSerializer`
  pom.xml
  src/main/java/net/sf/json/xml/JSONTypes.java
  src/main/java/net/sf/json/xml/XMLSerializer.java
  src/main/java/net/sf/json/xml/package-info.java
  src/test/java/net/sf/json/JSONTestSuite.java
  src/test/java/net/sf/json/xml/AllTests.java
  src/test/java/net/sf/json/xml/TestUserSubmitted.java
  src/test/java/net/sf/json/xml/TestXMLSerializer_reads.java
  src/test/java/net/sf/json/xml/TestXMLSerializer_writes.java
Labels: removed

#77 fix: CharacterObjectArrayMorpher throws exception
  src/main/java/net/sf/ezmorph/array/CharacterObjectArrayMorpher.java
Labels: bug

#75 Remove `JSONFunction` class and related functionality
  src/main/java/net/sf/json/AbstractJSON.java
  src/main/java/net/sf/json/JSONArray.java
  src/main/java/net/sf/json/JSONFunction.java
  src/main/java/net/sf/json/JSONObject.java
  src/main/java/net/sf/json/processors/JsonVerifier.java
  src/main/java/net/sf/json/test/JSONAssert.java
  src/main/java/net/sf/json/util/JSONTokener.java
  src/main/java/net/sf/json/util/JSONUtils.java
  src/site/xdoc/groovy.xml
  src/site/xdoc/index.xml
  src/site/xdoc/snippets.xml
  src/site/xdoc/usage.xml
  src/test/java/net/sf/json/AllTests.java
  src/test/java/net/sf/json/Assertions.java
  src/test/java/net/sf/json/PropertyConstants.java
  src/test/java/net/sf/json/TestJSONArray.java
  src/test/java/net/sf/json/TestJSONArrayAsList.java
  src/test/java/net/sf/json/TestJSONArrayCollections.java
  src/test/java/net/sf/json/TestJSONArrayEqualsHashCodeCompareTo.java
  src/test/java/net/sf/json/TestJSONArrayStaticBuilders_JSONString.java
  src/test/java/net/sf/json/TestJSONArrayStaticBuilders_String.java
  src/test/java/net/sf/json/TestJSONFunction.java
  src/test/java/net/sf/json/TestJSONObject.java
  src/test/java/net/sf/json/TestJSONObjectAsMap.java
  src/test/java/net/sf/json/TestJSONObjectEqualsHashCodeCompareTo.java
  src/test/java/net/sf/json/TestJSONObjectEvents.java
  src/test/java/net/sf/json/TestJSONObjectStaticBuilders_JSONString.java
  src/test/java/net/sf/json/TestJSONObjectStaticBuilders_JSONTokener.java
  src/test/java/net/sf/json/TestJSONObjectStaticBuilders_String.java
  src/test/java/net/sf/json/TestJSONSerializer.java
  src/test/java/net/sf/json/TestUserSubmitted.java
  src/test/java/net/sf/json/sample/BeanWithFunc.java
  src/test/java/net/sf/json/sample/ObjectBean.java
  src/test/java/net/sf/json/sample/PrimitiveBean.java
  src/test/java/net/sf/json/test/TestJSONAssert.java
  src/test/java/net/sf/json/util/TestJSONBuilder.java
  src/test/java/net/sf/json/util/TestJSONStringer.java
  src/test/java/net/sf/json/util/TestJSONUtils.java
Labels: removed

#78 refactor: move test utilities from main to test directory
  src/main/java/net/sf/ezmorph/test/package-info.java
  src/main/java/net/sf/json/test/package-info.java
  src/test/java/net/sf/ezmorph/test/ArrayAssertions.java
  src/test/java/net/sf/json/test/JSONAssert.java
Labels: test

#81 refactor: remove `JsonSlurper` and `JsonGroovyBuilder` class
  pom.xml
  src/main/java/net/sf/json/groovy/JsonGroovyBuilder.java
  src/main/java/net/sf/json/groovy/JsonSlurper.java
  src/main/java/net/sf/json/groovy/package-info.java
  src/site/site.xml
  src/site/xdoc/features.xml
  src/site/xdoc/groovy.xml
  src/site/xdoc/index.xml
  src/site/xdoc/snippets.xml
  src/test/resources/net/sf/json/groovy/sample.json
Labels: removed
